// Authentication
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// Errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PASSWORD_MISMATCH = "PASSWORD_MISMATCH";

// Users
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_TEACHERS = "GET_TEACHERS";
export const GET_USER = "GET_USER";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_TEACHER = "DELETE_TEACHER";

// Courses
export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const GET_REGISTERED_STUDENTS = "GET_REGISTERED_STUDENTS";
export const GET_NONREGISTERED_STUDENTS = "GET_NONREGISTERED_STUDENTS";

// Test
export const GET_TESTBASE_LIST = "GET_TESTBASE_LIST";
export const GET_STUDENT_COMPLETED_TESTS = "GET_STUDENT_COMPLETED_TESTS";
export const GET_TEST = "GET_TEST";

// News
export const GET_NEWS_LIST = "GET_NEWS_LIST";
export const GET_NEWS_COUNT = "GET_NEWS_COUNT";
export const GET_NEWS_SINGLE = "GET_NEWS_SINGLE";
export const SET_NEWS_LOADING = "SET_NEWS_LOADING";
export const SET_NEWS_LOADED = "SET_NEWS_LOADED";

// Lectures
export const GET_LECTURES = "GET_LECTURES";
export const SET_LECTURES_LOADING = "SET_LECTURES_LOADING";
export const SET_LECTURES_LOADED = "SET_LECTURES_LOADED";
// Lecture-Materials
export const ADD_LECTURE_MATERIALS = "ADD_LECTURE_MATERIALS";
export const REMOVE_MATERIAL = "REMOVE_MATERIAL";